MAX_PLAYERS = 2
FIRST_LEVEL = 1
MAX_LEVEL_NUMBER = 99

FIRST_PLAYER = 1
SECOND_PLAYER = 2

MAPS_PATH = "./maps/"
MAPS_FILENAME_PREFIX = "level_"
MAPS_FILE_EXTENSION = ".csv"

PIXEL_FACTOR = 10
MAP_ROWS = 10
MAP_COLUMNS = 10
MAP_ROW_POSITIONS = 2
MAP_COLUMN_POSITIONS = 2
MAP_HEIGHT_POSITIONS = MAP_ROWS * MAP_ROW_POSITIONS
MAP_WIDTH_POSITIONS = MAP_COLUMNS * MAP_COLUMN_POSITIONS

TO_STRING_BOT = "Bot"
TO_STRING_PLAYER = "Player %s"
TO_STRING_LEVEL = "Level %s"
TO_STRING_OBJECT = "%s at position %s size %s"
TO_STRING_TANK = "Tank"

TO_STRING_GAME = """
Game summary:
    Players: %s
    Level: %s
        Map: %s
"""