MAPS_PATH = "./maps/"
MAPS_FILENAME_PREFIX = "level_"
MAPS_FILE_EXTENSION = ".csv"

PIXEL_FACTOR = 10
MAP_ROWS = 10
MAP_COLUMNS = 10
MAP_ROW_POSITIONS = 2
MAP_COLUMN_POSITIONS = 2
MAP_HEIGHT = MAP_ROWS * MAP_ROW_POSITIONS
MAP_WIDTH = MAP_COLUMNS * MAP_COLUMN_POSITIONS