from .SolidMapObject import SolidMapObject
from .MovableMapObject import MovableMapObject
from .CompoundMapObject import CompoundMapObject
from .PassableMapObject import PassableMapObject
from .SolidMapObjectCompound import SolidMapObjectCompound
from .PassableMapObjectCompound import PassableMapObjectCompound
